const sentences=[
 'Găina galbenă gătește gogoși gigantice.','Cinci maimuțe mănâncă mămăligă marți.','Bunica beatbox-uiește brusc în bucătărie.','Șapte șosete supărate sar singure.','Un bursuc bărbos bea borș de burtă.','Rața dansatoare dă din aripi la discotecă.','Pinguinul parfumat preferă pizza picantă.','Veverița veselă vinde violete violet.','Melcul mecanic merge mereu miercurea.','Cârtița cochetă caută căpșuni crocante.','Broasca bretonată brodează brioșe albastre.','Papagalul poartă pantaloni portocalii.','Un crocodil curios croșetează cravate crem.','Pisica plinuță plimbă papuci prin ploaie.','Leul leneș linge limonadă lunea.','Șoricelul șmecher șoptește știri șocante.','O oaie obosită organizează o omletă.','Vulpea vopsită valsează vineri verde.','Trei tigri triști trag tramvaiul.','Cocoșul cochet cântă colinde confuze.'
];
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];let players=[{name:'Andrei',score:0},{name:'Maria',score:0}],duration=60,timeLeft=60,active=0,cardIndex=0,timer=null,started=false;
function renderPlayers(){ $('#playersList').innerHTML=players.map((p,i)=>`<div class="player-row"><span class="player-number">${i+1}</span><input class="player-input" data-index="${i}" value="${p.name}" maxlength="18" aria-label="Numele jucătorului ${i+1}">${players.length>1?`<button class="remove-player" data-remove="${i}" aria-label="Șterge jucătorul">×</button>`:''}</div>`).join('');$('#playerCountLabel').textContent=`${players.length} jucător${players.length===1?'':'i'}`;$$('.player-input').forEach(x=>x.oninput=e=>players[+e.target.dataset.index].name=e.target.value||`Jucător ${+e.target.dataset.index+1}`);$$('[data-remove]').forEach(x=>x.onclick=()=>{players.splice(+x.dataset.remove,1);renderPlayers()})}
renderPlayers();$('#addPlayerButton').onclick=()=>{if(players.length<8){players.push({name:`Jucător ${players.length+1}`,score:0});renderPlayers()}else alert('Puteți avea maximum 8 jucători.')};$$('.duration-options button').forEach(b=>b.onclick=()=>{$$('.duration-options button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');duration=b.dataset.duration==='custom'?+$('#customDuration').value: +b.dataset.duration;$('#customDuration').classList.toggle('hidden',b.dataset.duration!=='custom')});$('#customDuration').oninput=e=>duration=Math.max(10,Math.min(300,+e.target.value||45));
function switchScreen(id){$$('.screen').forEach(s=>s.classList.remove('active'));$('#'+id).classList.add('active')}
function updateTimer(){let progress=Math.max(0,timeLeft/duration*100);$('#timerValue').textContent=timeLeft;$('#timerRing').style.background=`conic-gradient(var(--orange) ${progress}%,#eceae4 0)`;$('#timerRing').classList.toggle('warning',timeLeft<=10);if(timeLeft<=0){clearInterval(timer);timer=null;$('#hint').textContent='Timpul a expirat! Schimbă jucătorul.';nextTurn()}}
function startTimer(){clearInterval(timer);timer=setInterval(()=>{timeLeft--;updateTimer();if(timeLeft<=0)clearInterval(timer)},1000)}
function showCard(){if(!started){started=true;startTimer()}$('#flashCard').classList.add('reveal');setTimeout(()=>$('#flashCard').classList.remove('reveal'),300);$('#sentenceText').textContent=sentences[cardIndex%sentences.length];$('#cardNumber').textContent='#'+String(cardIndex+1).padStart(2,'0');$('#showButton').classList.add('hidden');$('#resultActions').classList.remove('hidden');$('#gameHint').textContent='Cei care ascultă încearcă să ghicească!'}
function nextTurn(){players[active].name=players[active].name||`Jucător ${active+1}`;active=(active+1)%players.length;timeLeft=duration;started=false;cardIndex++;$('#activePlayerName').textContent=players[active].name;$('#roundLabel').textContent=`TURA ${Math.floor(cardIndex/players.length)+1}`;$('#showButton').classList.remove('hidden');$('#resultActions').classList.add('hidden');$('#gameHint').textContent='Apasă „Arată propoziția” și încearcă să o spui.';updateTimer()}
$('#startButton').onclick=()=>{duration=Math.max(10,duration);players.forEach(p=>p.score=0);active=0;cardIndex=0;timeLeft=duration;$('#activePlayerName').textContent=players[0].name;switchScreen('gameScreen');updateTimer()};$('#showButton').onclick=showCard;$('#correctButton').onclick=()=>{players[active].score++;nextTurn()};$('#skipButton').onclick=nextTurn;$('#quitButton').onclick=()=>{clearInterval(timer);switchScreen('setupScreen')};$('#scoreButton').onclick=()=>{clearInterval(timer);$('#scoreList').innerHTML=[...players].sort((a,b)=>b.score-a.score).map((p,i)=>`<div class="score-row"><span class="rank">${i+1}</span><span class="score-avatar">${['😎','🤪','🦄','🐸','🦊','🐼','🐙','🦁'][i]}</span><span class="score-name">${p.name}</span><span class="points">${p.score} <small>puncte</small></span></div>`).join('');switchScreen('scoreScreen')};$('#scoreBackButton').onclick=()=>{switchScreen('gameScreen');if(started)startTimer()};$('#newGameButton').onclick=()=>{players.forEach(p=>p.score=0);switchScreen('setupScreen')};$('#helpButton').onclick=()=>$('#helpDialog').showModal();$('#closeHelp').onclick=()=>$('#helpDialog').close();$('#helpDialog').addEventListener('click',e=>{if(e.target===e.currentTarget)e.currentTarget.close()});
